# Generated by Django 5.0.9 on 2024-10-10 10:19

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=2)),
                ('country_code', models.CharField(max_length=3)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None)),
                ('account_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='mydb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('formid', models.CharField(max_length=50)),
                ('apiVersion', models.CharField(max_length=50)),
                ('modelId', models.CharField(max_length=50)),
                ('field_name', models.CharField(max_length=100)),
                ('OCR_value', models.CharField(max_length=255)),
                ('Edited_value', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'ds_ocr_exp',
            },
        ),
    ]
