# Generated by Django 5.0.9 on 2024-10-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uiocrapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydb',
            name='full_name',
        ),
    ]
