# Generated by Django 5.0.9 on 2024-10-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiocrapp', '0002_remove_mydb_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
