# Generated by Django 5.0.9 on 2024-10-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiocrapp', '0003_customerinfo_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='Address',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='Amount',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='Date',
            field=models.CharField(default=1.0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='FileName',
            field=models.CharField(default=1.0, max_length=50),
            preserve_default=False,
        ),
    ]
